project:
  type: website
  output-dir: _site

website:
  title: ""              # 不显示站点标题
  bread-crumbs: false    # 关闭面包屑
  navbar:
    title: false         # 隐藏左侧品牌文字
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: visualizations.qmd
        text: Visualizations
      - href: teaching_notes.qmd
        text: Teaching and Notes
      - href: news.qmd
        text: News
    search: true
    background: light
  page-footer:
    center: "© Jiangchao QIU"

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: false
