project:
  type: website
  output-dir: _site

website:
  title: ""              # Do not display site title
  site-url: https://qiujiangchao.github.io
  bread-crumbs: false    # Disable breadcrumbs
  favicon: assets/favicon.ico   # Browser tab icon
  navbar:
    title: false         # Hide brand text on the left
    right:
      - href: home.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: visualizations.qmd
        text: Visualizations
      - href: teaching.qmd
        text: Teaching
      - href: news.qmd
        text: News
    search: true
    background: light
  page-footer:
    center: "© Jiangchao QIU"

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <!-- SVG favicon (modern browsers) -->
        <link rel="icon" type="image/svg+xml" href="assets/favicon.svg">
        <!-- iOS home screen icon -->
        <link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png">
