project:
  type: website
  output-dir: _site

website:
  title: ""            # do not show site title in navbar
  navbar:
    title: false       # extra safeguard to hide brand text
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: news.qmd
        text: News
      - href: cv.qmd
        text: CV
    search: true
    background: light
  page-footer:
    center: "© Jiangchao QIU"

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: false
