project:
  type: website
  output-dir: _site

website:
  title: "Jiangchao QIU"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: news.qmd
        text: News
      - href: cv.qmd
        text: CV
    search: true
    background: light   # 顶部导航浅色（白色）
  page-footer:
    center: "© Jiangchao QIU"

format:
  html:
    theme:
      light: cosmo      # 白底简洁主题（可换 lumen/minty/materia 等）
    css: styles.css     # 自定义样式（见下）
    toc: false
